dbt_first_proj:  # your profile name from dbt_project.yml
  target: dev  # your development environment
  outputs:
    
    dev:
      type: bigquery
      method: service-account
      project: dbt-express  # name of the project in BigQuery
      dataset: dbt_first_proj  # your dataset for development (usually your name)
      threads: 4
      keyfile: dbt-user.json
      timeout_seconds: 300
      priority: interactive
      retries: 1
    
    prod: # your production environment
      type: bigquery
      method: service-account
      project: dbt-express  # name of the project in BigQuery
      dataset: dbt_first_proj  # your dataset for development (usually your name)
      threads: 4
      keyfile: dbt-user.json
      timeout_seconds: 300
      priority: interactive
      retries: 1
